-- Fantasy Playbook — NFL Player Seed Data
-- Run this AFTER migration.sql in Supabase SQL Editor

insert into public.nfl_players (name, team, position) values
-- Quarterbacks
('Patrick Mahomes', 'KC', 'QB'),
('Josh Allen', 'BUF', 'QB'),
('Lamar Jackson', 'BAL', 'QB'),
('Jalen Hurts', 'PHI', 'QB'),
('Joe Burrow', 'CIN', 'QB'),
('Dak Prescott', 'DAL', 'QB'),
('Tua Tagovailoa', 'MIA', 'QB'),
('Justin Herbert', 'LAC', 'QB'),
('Jordan Love', 'GB', 'QB'),
('Jared Goff', 'DET', 'QB'),
('C.J. Stroud', 'HOU', 'QB'),
('Brock Purdy', 'SF', 'QB'),
('Trevor Lawrence', 'JAX', 'QB'),
('Anthony Richardson', 'IND', 'QB'),
('Kyler Murray', 'ARI', 'QB'),
('Baker Mayfield', 'TB', 'QB'),
('Sam Darnold', 'MIN', 'QB'),
('Geno Smith', 'SEA', 'QB'),
('Matthew Stafford', 'LAR', 'QB'),
('Caleb Williams', 'CHI', 'QB'),
('Jayden Daniels', 'WAS', 'QB'),
('Drake Maye', 'NE', 'QB'),
('Bo Nix', 'DEN', 'QB'),
('Russell Wilson', 'PIT', 'QB'),
('Kirk Cousins', 'ATL', 'QB'),
('Daniel Jones', 'NYG', 'QB'),
('Aaron Rodgers', 'NYJ', 'QB'),
('Deshaun Watson', 'CLE', 'QB'),
('Will Levis', 'TEN', 'QB'),
('Bryce Young', 'CAR', 'QB'),
('Aidan OConnell', 'LV', 'QB'),
('Gardner Minshew', 'LV', 'QB'),

-- Running Backs
('Christian McCaffrey', 'SF', 'RB'),
('Breece Hall', 'NYJ', 'RB'),
('Bijan Robinson', 'ATL', 'RB'),
('Saquon Barkley', 'PHI', 'RB'),
('Jahmyr Gibbs', 'DET', 'RB'),
('David Montgomery', 'DET', 'RB'),
('Jonathan Taylor', 'IND', 'RB'),
('Derrick Henry', 'BAL', 'RB'),
('Josh Jacobs', 'GB', 'RB'),
('Kyren Williams', 'LAR', 'RB'),
('De Von Achane', 'MIA', 'RB'),
('Isiah Pacheco', 'KC', 'RB'),
('Travis Etienne', 'JAX', 'RB'),
('Kenneth Walker III', 'SEA', 'RB'),
('Alvin Kamara', 'NO', 'RB'),
('Joe Mixon', 'HOU', 'RB'),
('Aaron Jones', 'MIN', 'RB'),
('Tony Pollard', 'TEN', 'RB'),
('Rachaad White', 'TB', 'RB'),
('James Cook', 'BUF', 'RB'),
('Rhamondre Stevenson', 'NE', 'RB'),
('Zack Moss', 'CIN', 'RB'),
('James Conner', 'ARI', 'RB'),
('Javonte Williams', 'DEN', 'RB'),
('Nick Chubb', 'CLE', 'RB'),
('Najee Harris', 'PIT', 'RB'),
('D Andre Swift', 'CHI', 'RB'),
('Brian Robinson Jr', 'WAS', 'RB'),
('Chuba Hubbard', 'CAR', 'RB'),
('Jerome Ford', 'CLE', 'RB'),
('Devin Singletary', 'NYG', 'RB'),
('Jaylen Warren', 'PIT', 'RB'),
('Zamir White', 'LV', 'RB'),
('Tyler Allgeier', 'ATL', 'RB'),
('Gus Edwards', 'LAC', 'RB'),
('Rico Dowdle', 'DAL', 'RB'),
('Chase Brown', 'CIN', 'RB'),
('Tyjae Spears', 'TEN', 'RB'),
('Raheem Mostert', 'MIA', 'RB'),
('Rashid Shaheed', 'NO', 'RB'),

-- Wide Receivers
('Tyreek Hill', 'MIA', 'WR'),
('CeeDee Lamb', 'DAL', 'WR'),
('Amon-Ra St. Brown', 'DET', 'WR'),
('Ja''Marr Chase', 'CIN', 'WR'),
('A.J. Brown', 'PHI', 'WR'),
('Justin Jefferson', 'MIN', 'WR'),
('Davante Adams', 'NYJ', 'WR'),
('Stefon Diggs', 'HOU', 'WR'),
('Nico Collins', 'HOU', 'WR'),
('Garrett Wilson', 'NYJ', 'WR'),
('DK Metcalf', 'SEA', 'WR'),
('DeVonta Smith', 'PHI', 'WR'),
('Brandon Aiyuk', 'SF', 'WR'),
('Chris Olave', 'NO', 'WR'),
('Mike Evans', 'TB', 'WR'),
('Chris Godwin', 'TB', 'WR'),
('Deebo Samuel', 'SF', 'WR'),
('Drake London', 'ATL', 'WR'),
('DJ Moore', 'CHI', 'WR'),
('Terry McLaurin', 'WAS', 'WR'),
('Tank Dell', 'HOU', 'WR'),
('Jaylen Waddle', 'MIA', 'WR'),
('Puka Nacua', 'LAR', 'WR'),
('Cooper Kupp', 'LAR', 'WR'),
('Rashee Rice', 'KC', 'WR'),
('Amari Cooper', 'CLE', 'WR'),
('Michael Pittman Jr', 'IND', 'WR'),
('George Pickens', 'PIT', 'WR'),
('Keenan Allen', 'CHI', 'WR'),
('Zay Flowers', 'BAL', 'WR'),
('DeAndre Hopkins', 'TEN', 'WR'),
('Calvin Ridley', 'TEN', 'WR'),
('Diontae Johnson', 'CAR', 'WR'),
('Courtland Sutton', 'DEN', 'WR'),
('Christian Watson', 'GB', 'WR'),
('Romeo Doubs', 'GB', 'WR'),
('Ladd McConkey', 'LAC', 'WR'),
('Quentin Johnston', 'LAC', 'WR'),
('Jaxon Smith-Njigba', 'SEA', 'WR'),
('Jayden Reed', 'GB', 'WR'),
('Darnell Mooney', 'ATL', 'WR'),
('Malik Nabers', 'NYG', 'WR'),
('Marvin Harrison Jr', 'ARI', 'WR'),
('Rome Odunze', 'CHI', 'WR'),
('Brian Thomas Jr', 'JAX', 'WR'),
('Xavier Worthy', 'KC', 'WR'),
('Wan''Dale Robinson', 'NYG', 'WR'),
('Khalil Shakir', 'BUF', 'WR'),
('Curtis Samuel', 'BUF', 'WR'),
('Jameson Williams', 'DET', 'WR'),

-- Tight Ends
('Travis Kelce', 'KC', 'TE'),
('Sam LaPorta', 'DET', 'TE'),
('Mark Andrews', 'BAL', 'TE'),
('T.J. Hockenson', 'MIN', 'TE'),
('George Kittle', 'SF', 'TE'),
('Evan Engram', 'JAX', 'TE'),
('Dallas Goedert', 'PHI', 'TE'),
('David Njoku', 'CLE', 'TE'),
('Kyle Pitts', 'ATL', 'TE'),
('Jake Ferguson', 'DAL', 'TE'),
('Dalton Kincaid', 'BUF', 'TE'),
('Pat Freiermuth', 'PIT', 'TE'),
('Cole Kmet', 'CHI', 'TE'),
('Trey McBride', 'ARI', 'TE'),
('Dalton Schultz', 'HOU', 'TE'),
('Jonnu Smith', 'MIA', 'TE'),
('Brock Bowers', 'LV', 'TE'),
('Chigoziem Okonkwo', 'TEN', 'TE'),
('Tucker Kraft', 'GB', 'TE'),
('Isaiah Likely', 'BAL', 'TE');
